Tempo: test/AlarmTest.cpp File Reference
AlarmTest.cpp File Reference
#include <cassert>
#include <iostream>
#include <chrono>
#include <thread>
#include "../include/Alarm.hpp"
Functions
void test_alarm ()
int main ()
Function Documentation
main()
int main (void)
Definition at line 21 of file AlarmTest.cpp.
           {
    try {
        test_alarm();
        cout << "All tests passed successfully!\n";
    } catch (const exception& e) {
        cerr << "Test failed with exception: " << e.what() << std::endl;
        return 1;
    }
    return 0;
}
References test_alarm().
test_alarm()
void test_alarm ()
Definition at line 10 of file AlarmTest.cpp.
                 {
    Alarm alarm(0,0);
    string start = alarm.timeToString(alarm.getEndTime());
    double percent = alarm.percentElapsed();
    int remaining = alarm.remainingMilliseconds();
    bool runing = alarm.isRunning();
    bool done = alarm.isDone();
}
References Alarm::getEndTime(), Alarm::isDone(), Alarm::isRunning(), Alarm::percentElapsed(), Alarm::remainingMilliseconds(), and Alarm::timeToString().
Referenced by main().