Tempo: test/DisplayTest.cpp File Reference
DisplayTest.cpp File Reference
#include <cassert>
#include <iostream>
#include <chrono>
#include <thread>
#include "../include/Display.hpp"
Functions
void test_nonreturn ()
void test_timer_setup ()
void test_timer ()
void test_stopwatch ()
void test_alarm ()
void test_alarm_setup ()
int main ()
Function Documentation
main()
int main (void)
Definition at line 54 of file DisplayTest.cpp.
           {
    try {
        test_nonreturn();
        test_timer_setup();
        test_timer();
        test_stopwatch();
        test_alarm();
        test_alarm_setup();
        cout << "All tests passed successfully!\n";
    } catch (const exception& e) {
        cerr << "Test failed with exception: " << e.what() << std::endl;
        return 1;
    }
    return 0;
}
References test_alarm(), test_alarm_setup(), test_nonreturn(), test_stopwatch(), test_timer(), and test_timer_setup().
test_alarm()
void test_alarm ()
Definition at line 42 of file DisplayTest.cpp.
                 {
    Display display;
    Alarm alarm(12,12);
    display.tickAlarm(alarm);
}
References Display::tickAlarm().
Referenced by main().
test_alarm_setup()
void test_alarm_setup ()
Definition at line 48 of file DisplayTest.cpp.
                       {
    Display display;
    display.tickAlarmSetup("00:00", false);
    display.tickAlarmSetup("12:12", true);
}
References Display::tickAlarmSetup().
Referenced by main().
test_nonreturn()
void test_nonreturn ()
Definition at line 10 of file DisplayTest.cpp.
                     {
    Display display;
    display.clearScreen();
    string sss = "Testing";
    display.fast_print(sss);
    display.setCursor(1,1);
    display.clearLine(1);
    display.setSplash(sss);
    display.clearSplash();
}
References Display::clearLine(), Display::clearScreen(), Display::clearSplash(), Display::fast_print(), Display::setCursor(), and Display::setSplash().
Referenced by main().
test_stopwatch()
void test_stopwatch ()
Definition at line 35 of file DisplayTest.cpp.
                     {
    Display display;
    Stopwatch stopwatch;
    stopwatch.addSplit();
    display.tickStopwatch(stopwatch);
}
References Stopwatch::addSplit(), and Display::tickStopwatch().
Referenced by main().
test_timer()
void test_timer ()
Definition at line 27 of file DisplayTest.cpp.
                 {
    Display display;
    Timer timer(1,1,1);
    display.tickTimer(timer);
    timer.pause();
    display.tickTimer(timer);
}
References Timer::pause(), and Display::tickTimer().
Referenced by main().
test_timer_setup()
void test_timer_setup ()
Definition at line 22 of file DisplayTest.cpp.
                       {
    Display display;
    display.tickTimerSetup("00:00:00");
}
References Display::tickTimerSetup().
Referenced by main().