Tempo: test/MenuTest.cpp File Reference
MenuTest.cpp File Reference
#include <cassert>
#include <iostream>
#include <chrono>
#include <thread>
#include "../include/Menu.hpp"
Functions
void test_menu ()
int main ()
Function Documentation
main()
int main (void)
Definition at line 21 of file MenuTest.cpp.
           {
    try {
        test_menu();
        cout << "All tests passed successfully!\n";
    } catch (const exception& e) {
        cerr << "Test failed with exception: " << e.what() << std::endl;
        return 1;
    }
    return 0;
}
References test_menu().
test_menu()
void test_menu ()
Definition at line 10 of file MenuTest.cpp.
                {
    Menu menu(true);
    menu.saveSettings();
    menu.loadSettings();
    menu.settingsMenu(1);
    menu.settingsMenu(2);
    menu.settingsMenu(3);
    return;
}
References Menu::loadSettings(), Menu::saveSettings(), and Menu::settingsMenu().
Referenced by main().