Tempo: src/Notification.cpp File Reference
Notification.cpp File Reference
#include <windows.h>
#include <shellapi.h>
Macros
#define WM_TRAYICON (WM_USER + 1)
Functions
LRESULT CALLBACK WindowProcedure (HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam)
Window procedure for handling messages.
void ShowNotification (HINSTANCE hInstance, HWND hwnd)
Shows a notification in the system tray.
int APIENTRY WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
Entry point for the Windows application.
Macro Definition Documentation
WM_TRAYICON
#define WM_TRAYICON (WM_USER + 1)
Definition at line 8 of file Notification.cpp.
Function Documentation
ShowNotification()
void ShowNotification (HINSTANCE hInstance, HWND hwnd)
Shows a notification in the system tray.
This function adds a notification icon to the system tray and displays a notification message.
Parameters
hInstance Handle to the application instance.
hwnd Handle to the window.
Definition at line 53 of file Notification.cpp.
{
    NOTIFYICONDATA nid = { 0 };
    nid.cbSize = sizeof(nid);
    nid.hWnd = hwnd;
    nid.uID = 1001;
    nid.uFlags = NIF_ICON | NIF_MESSAGE | NIF_TIP | NIF_INFO;
    nid.uCallbackMessage = WM_TRAYICON; // Custom message for icon interactions
    nid.hIcon = LoadIcon(NULL, IDI_APPLICATION);
    strcpy_s(nid.szTip, "My Notification App");
    strcpy_s(nid.szInfo, "Hello! This is your notification.");
    strcpy_s(nid.szInfoTitle, "Notification Title");
    nid.dwInfoFlags = NIIF_INFO;
    Shell_NotifyIcon(NIM_ADD, &nid);
}
References WM_TRAYICON.
Referenced by WinMain().
WindowProcedure()
LRESULT CALLBACK WindowProcedure (HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam)
Window procedure for handling messages.
This function processes messages sent to the window, including custom tray icon messages and window destruction.
Parameters
hwnd Handle to the window.
message The message identifier.
wParam Additional message information.
lParam Additional message information.
Returns
LRESULT The result of the message processing.
Definition at line 25 of file Notification.cpp.
{
    switch (message) {
        case WM_TRAYICON:
            if (lParam == WM_LBUTTONUP) {
                MessageBox(NULL, "You clicked the notification icon!", "Notification", MB_OK);
            }
            break;
        case WM_DESTROY:
            PostQuitMessage(0);
            break;
        default:
            return DefWindowProc(hwnd, message, wParam, lParam);
    }
    return 0;
}
References WM_TRAYICON.
Referenced by WinMain().
WinMain()
int APIENTRY WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
Entry point for the Windows application.
This function initializes the application, creates a window, and enters the message loop.
Parameters
hInstance Handle to the application instance.
hPrevInstance Handle to the previous instance (always NULL for Win32).
lpCmdLine Command line arguments.
nCmdShow How the window should be shown.
Returns
int The exit code of the application.
Definition at line 84 of file Notification.cpp.
{
    const char CLASS_NAME[] = "NotificationApp";
    WNDCLASS wc = { 0 };
    wc.lpfnWndProc = WindowProcedure;
    wc.hInstance = hInstance;
    wc.lpszClassName = CLASS_NAME;
    RegisterClass(&wc);
    HWND hwnd = CreateWindowEx(0, CLASS_NAME, "Notification Window", 0, 0, 0, 0, 0, NULL, NULL, hInstance, NULL);
    if (hwnd == NULL) {
        return 0;
    }
    ShowNotification(hInstance, hwnd);
    MSG msg;
    while (GetMessage(&msg, NULL, 0, 0)) {
        TranslateMessage(&msg);
        DispatchMessage(&msg);
    }
    return 0;
}
References ShowNotification(), and WindowProcedure().