Tempo: test/StopwatchTest.cpp File Reference
StopwatchTest.cpp File Reference
#include <cassert>
#include <iostream>
#include <chrono>
#include <thread>
#include "../include/Stopwatch.hpp"
Functions
void test_constructor ()
void test_pause_resume ()
void test_reset ()
void test_splits ()
int main ()
Function Documentation
main()
int main (void)
Definition at line 53 of file StopwatchTest.cpp.
           {
    try {
        test_constructor();
        test_pause_resume();
        test_reset();
        test_splits();
        cout << "All tests passed successfully!\n";
    }
    catch (const exception& e) {
        cerr << "Test failed with exception: " << e.what() << endl;
        return 1;
    }
    return 0;
}
References test_constructor(), test_pause_resume(), test_reset(), and test_splits().
test_constructor()
void test_constructor ()
Definition at line 10 of file StopwatchTest.cpp.
{
    Stopwatch stopwatch(0,0,0);
    assert(stopwatch.currentMilliseconds() == 0);
    stopwatch.start();
    assert(stopwatch.isRunning());
    cout << "Constructor test passed.\n";
}
References Stopwatch::currentMilliseconds(), Stopwatch::isRunning(), and Stopwatch::start().
Referenced by main().
test_pause_resume()
void test_pause_resume ()
Definition at line 18 of file StopwatchTest.cpp.
{
    Stopwatch stopwatch(0, 0, 0);
    this_thread::sleep_for(chrono::milliseconds(10));
    stopwatch.pause();
    int currentAfterPause = stopwatch.currentMilliseconds();
    assert(!stopwatch.isRunning());
    this_thread::sleep_for(chrono::milliseconds(10));
    assert(stopwatch.currentMilliseconds() == currentAfterPause);
    stopwatch.resume();
    assert(stopwatch.isRunning());
    assert(stopwatch.currentMilliseconds() >= 10);
    cout << "Pause and resume test passed.\n";
}
References Stopwatch::currentMilliseconds(), Stopwatch::isRunning(), Stopwatch::pause(), and Stopwatch::resume().
Referenced by main().
test_reset()
void test_reset ()
Definition at line 32 of file StopwatchTest.cpp.
                  {
    Stopwatch stopwatch(0, 0, 0);
    stopwatch.start();
    this_thread::sleep_for(chrono::milliseconds(10));
    stopwatch.reset();
    assert(stopwatch.currentMilliseconds() == 0);
    assert(!stopwatch.isRunning());
    cout << "Reset test passed.\n";
}
References Stopwatch::currentMilliseconds(), Stopwatch::isRunning(), Stopwatch::reset(), and Stopwatch::start().
Referenced by main().
test_splits()
void test_splits ()
Definition at line 42 of file StopwatchTest.cpp.
                   {
    Stopwatch stopwatch(0, 0, 0);
    stopwatch.start();
    this_thread::sleep_for(chrono::milliseconds(10));
    stopwatch.addSplit();
    assert(stopwatch.getSplits().at(0) > 0 && stopwatch.getSplits().at(0) <= 20);
    stopwatch.clearSplits();
    assert(stopwatch.getSplits().empty());
    cout << "Split tests passed.\n";
}
References Stopwatch::addSplit(), Stopwatch::clearSplits(), Stopwatch::getSplits(), and Stopwatch::start().
Referenced by main().