Tempo: tests/TimerTest.cpp File Reference
TimerTest.cpp File Reference
#include <cassert>
#include <iostream>
#include <chrono>
#include <thread>
#include "../include/Timer.hpp"
Functions
void test_constructor ()
void test_pause_resume ()
void test_reset ()
void test_add_time ()
void test_percent_elapsed ()
void test_expiration ()
int main ()
Function Documentation
main()
int main (void)
Definition at line 80 of file TimerTest.cpp.
           {
    try {
        test_constructor();
        test_pause_resume();
        test_reset();
        test_add_time();
        test_percent_elapsed();
        test_expiration();
        cout << "All tests passed successfully!\n";
    } catch (const exception& e) {
        cerr << "Test failed with exception: " << e.what() << std::endl;
        return 1;
    }
    return 0;
}
References test_add_time(), test_constructor(), test_expiration(), test_pause_resume(), test_percent_elapsed(), and test_reset().
test_add_time()
void test_add_time ()
Definition at line 50 of file TimerTest.cpp.
                     {
    Timer timer(0, 1, 0);
    timer.addTime(30);
    int timeRemaining = timer.remainingMilliseconds();
    assert(timeRemaining > 89995 && timeRemaining < 90001);
    std::cout << "test_add_time passed!\n";
}
References Timer::addTime(), and Timer::remainingMilliseconds().
Referenced by main().
test_constructor()
void test_constructor ()
Definition at line 10 of file TimerTest.cpp.
{
    Timer timer(0, 1, 0); // 1 minutes
    int timeRemaining = timer.remainingMilliseconds();
    assert(timeRemaining > 59995 && timeRemaining < 60001); // 5 Millisecond margin of error
    assert(timer.isRunning());
    cout << "test_constructor passed!\n";
}
References Timer::isRunning(), and Timer::remainingMilliseconds().
Referenced by main().
test_expiration()
void test_expiration ()
Definition at line 72 of file TimerTest.cpp.
                       {
    Timer timer(0, 0, 2); // 2 seconds
    this_thread::sleep_for(chrono::seconds(3));
    assert(timer.remainingMilliseconds() == 0);
    assert(!timer.isRunning());
    cout << "test_expiration passed!\n";
}
References Timer::isRunning(), and Timer::remainingMilliseconds().
Referenced by main().
test_pause_resume()
void test_pause_resume ()
Definition at line 21 of file TimerTest.cpp.
{
    Timer timer(0, 1, 0); // One minute
    this_thread::sleep_for(chrono::seconds(1));
    timer.pause();
    int timeRemaining = timer.remainingMilliseconds();
    assert(!timer.isRunning());
    this_thread::sleep_for(chrono::seconds(1));
    assert(timer.remainingMilliseconds() == timeRemaining);
    timer.resume();
    assert(timer.isRunning());
    assert(timer.remainingMilliseconds() < 59000);
    std::cout << "test_pause_resume passed!\n";
}
References Timer::isRunning(), Timer::pause(), Timer::remainingMilliseconds(), and Timer::resume().
Referenced by main().
test_percent_elapsed()
void test_percent_elapsed ()
Definition at line 61 of file TimerTest.cpp.
{
    Timer timer(0, 0, 4);
    this_thread::sleep_for(chrono::seconds(2));
    double percent = timer.percentElapsed();
    assert(percent > 49.0 && percent < 51.0); // allows for a bit or margin of error
    std::cout << "test_percent_elapsed passed!\n";
}
References Timer::percentElapsed().
Referenced by main().
test_reset()
void test_reset ()
Definition at line 38 of file TimerTest.cpp.
                  {
    Timer timer(0, 1, 0);
    this_thread::sleep_for(chrono::seconds(1));
    timer.reset();
    assert(timer.remainingMilliseconds() == 60000);
    assert(!timer.isRunning());
    std::cout << "test_reset passed!\n";
}
References Timer::isRunning(), Timer::remainingMilliseconds(), and Timer::reset().
Referenced by main().