Tempo: Timer Class Reference
Timer Class Reference
The Timer class provides a countdown timer with start, pause, resume, reset, and time adjustment functionalities.
#include <Timer.hpp>
Public Member Functions
Timer ()
Default constructor prompts the user to set a timer with a specific duration.
Timer (int hours, int minutes, int seconds)
Constructor to specify the timer duration directly in hours, minutes, and seconds.
void start (int countdownMilliseconds)
Starts the timer by setting the end time based on the current time plus the countdown duration.
void pause ()
Pauses the timer and calculates the remaining milliseconds.
void resume ()
Resumes the timer from where it was paused by recalculating the end time.
void reset ()
Resets the timer to its original duration and pauses it.
void addTime ()
void addTime (int seconds)
Adds a specified amount of time (in seconds) to the timer.
void changeIncrementTime ()
Allows the user to change the increment time used for adding time to the timer.
bool isRunning ()
Checks if the timer is currently running.
int remainingMilliseconds ()
Returns the remaining time in milliseconds.
double percentElapsed ()
Returns the percentage of time that has elapsed since the timer started.
Private Attributes
int _startMilliseconds
The initial duration of the timer in milliseconds.
int _countdownMilliseconds
The duration of the countdown in milliseconds.
int _remainingMilliseconds
The remaining time in milliseconds.
int _incrementMilliseconds
The increment time in milliseconds for adding time.
bool _running
Indicates whether the timer is currently running.
chrono::time_point< chrono::steady_clock > _endTime
The time point when the timer will end.
chrono::time_point< chrono::steady_clock > _pauseTime
The time point when the timer was paused.
Detailed Description
The Timer class provides a countdown timer with start, pause, resume, reset, and time adjustment functionalities.
Definition at line 13 of file Timer.hpp.
Constructor & Destructor Documentation
Timer() [1/2]
Timer::Timer ()
Default constructor prompts the user to set a timer with a specific duration.
The user can specify the duration in hours, minutes, and seconds. The timer is initialized and started based on the user input.
The user can specify the duration in hours, minutes, and seconds. The timer is initialized and started based on the user input.
Definition at line 16 of file Timer.cpp.
             {
    int h = 0;
    int m = 0;
    int s = 0;
    int countdownSeconds = 0;
    _incrementMilliseconds = 0;
    while (true) {
        cout << "How long would you like to set a timer for?" << endl;
        string input = "";
        getline(cin, input);
        // Regular expressions to match hours, minutes, and seconds
        regex hours_regex(R"((\d+)\s*hour?)");
        regex minutes_regex(R"((\d+)\s*minute?)");
        regex seconds_regex(R"((\d+)\s*second?)");
        smatch match;
        // Extract hours
        if (regex_search(input, match, hours_regex)) {
            h = stoi(match[1].str());
        }
        // Extract minutes
        if (regex_search(input, match, minutes_regex)) {
            m = stoi(match[1].str());
        }
        // Extract seconds
        if (regex_search(input, match, seconds_regex)) {
            s = stoi(match[1].str());
        }
        countdownSeconds = (3600 * h) + (60 * m) + (s);
        if (countdownSeconds == 0) {
            continue;
        }
        if (countdownSeconds <= 360000) {
            break;
        } else {
            cout << "Cannot set a timer for more than 100 hours." << endl;
        }
    }
    _startMilliseconds = countdownSeconds * 1000;
    _remainingMilliseconds = _startMilliseconds;
    _countdownMilliseconds = _startMilliseconds;
    start(_countdownMilliseconds);
}
References _countdownMilliseconds, _incrementMilliseconds, _remainingMilliseconds, _startMilliseconds, and start().
Timer() [2/2]
Timer::Timer (int hours, int minutes, int seconds)
Constructor to specify the timer duration directly in hours, minutes, and seconds.
Initializes and starts the timer with the specified duration.
Parameters
hours The number of hours to set.
minutes The number of minutes to set.
seconds The number of seconds to set.
Initializes and starts the timer with the specified duration.
Parameters
hours The number of hours to set.
minutes The number of minutes to set.
seconds The number of seconds to set.
Definition at line 75 of file Timer.cpp.
{
    int milli = 3600000 * hours + 60000 * minutes + 1000 * seconds;
    _countdownMilliseconds = milli;
    _remainingMilliseconds = milli;
    _startMilliseconds = milli;
    _incrementMilliseconds = 0;
    start(_countdownMilliseconds);
}
References _countdownMilliseconds, _incrementMilliseconds, _remainingMilliseconds, _startMilliseconds, and start().
Member Function Documentation
addTime() [1/2]
void Timer::addTime ()
Definition at line 162 of file Timer.cpp.
                   {
    bool wasRunning = _running;
    pause();
    if(!_incrementMilliseconds){
        changeIncrementTime();
    }
    _remainingMilliseconds += _incrementMilliseconds;
    _countdownMilliseconds += _incrementMilliseconds;
    if(_remainingMilliseconds >=  360000000){
        _remainingMilliseconds = 359999999;
        _countdownMilliseconds = 359999999;
    }
    if (wasRunning) {
        resume();
    }
}
References _countdownMilliseconds, _incrementMilliseconds, _remainingMilliseconds, _running, changeIncrementTime(), pause(), and resume().
addTime() [2/2]
void Timer::addTime (int seconds)
Adds a specified amount of time (in seconds) to the timer.
If the timer is running, it resumes after adding time.
Parameters
seconds The number of seconds to add to the timer.
If the timer is running, it resumes after adding time.
Parameters
seconds The number of seconds to add to the timer.
Definition at line 150 of file Timer.cpp.
{
    bool wasRunning = _running;
    pause();
    _remainingMilliseconds += 1000 * seconds;
    _countdownMilliseconds += 1000 * seconds;
    if(wasRunning){
        resume();
    }
}
References _countdownMilliseconds, _remainingMilliseconds, _running, pause(), and resume().
changeIncrementTime()
void Timer::changeIncrementTime ()
Allows the user to change the increment time used for adding time to the timer.
The increment time can be specified in hours, minutes, or seconds.
The increment time can be specified in hours, minutes, or seconds.
Definition at line 192 of file Timer.cpp.
{
    cout << "Enter the amount of time to add for each press: ";
    string input;
    cin >> input;
    // Regular expressions to match hours, minutes, and seconds
    regex hours_regex(R"((\d+)\s*hour?)");
    regex minutes_regex(R"((\d+)\s*minute?)");
    regex seconds_regex(R"((\d+)\s*second?)");
    smatch match;
    int newIncrementMilliseconds = 0;
    string unit;
    try {
        // Convert input to milliseconds based on what unit is specified
        if (regex_search(input, match, hours_regex)) {
            newIncrementMilliseconds = stoi(match[1].str()) * 3600000;
            unit = "hours";
        } else if (regex_search(input, match, minutes_regex)) {
            newIncrementMilliseconds = stoi(match[1].str()) * 60000;
            unit = "minutes";
        } else if (regex_search(input, match, seconds_regex)) {
            newIncrementMilliseconds = stoi(match[1].str()) * 1000;
            unit = "seconds";
        } else {
            cout << "Invalid input format. Increment time must be specified in hours, minutes, or seconds." << endl;
            return;
        }
        if (newIncrementMilliseconds <= 0) {
            cout << "Increment time must be a positive value. Keeping the previous value of " << _incrementMilliseconds << " milliseconds." << endl;
        } else {
            _incrementMilliseconds = newIncrementMilliseconds;
            cout << "Increment time set to " << match[1].str() << " " << unit << "." << endl;
        }
    } catch (invalid_argument& e) {
        cout << "Invalid input. Please enter a valid numeric value. Keeping the previous value of " << _incrementMilliseconds << " milliseconds." << endl;
    } catch (out_of_range& e) {
        cout << "The value is too large. Keeping the previous value of " << _incrementMilliseconds << " milliseconds." << endl;
    }
    std::this_thread::sleep_for(std::chrono::seconds(1));
    //cout << "\r\033[K"; // Clear the line after waiting for input
}
References _incrementMilliseconds.
Referenced by addTime().
isRunning()
bool Timer::isRunning ()
Checks if the timer is currently running.
Returns
bool True if the timer is running, false otherwise.
Returns
bool True if the timer is running, false otherwise.
Definition at line 276 of file Timer.cpp.
                      {
    return _running;
}
References _running.
Referenced by Menu::checkTimerInput().
pause()
void Timer::pause ()
Pauses the timer and calculates the remaining milliseconds.
Definition at line 105 of file Timer.cpp.
                  {
    if (_running) {
       _pauseTime = chrono::steady_clock::now();
       _remainingMilliseconds = chrono::duration_cast<chrono::milliseconds>(_endTime - _pauseTime).count();
       _running = false;
    }
}
References _endTime, _pauseTime, _remainingMilliseconds, and _running.
Referenced by addTime(), Menu::checkTimerInput(), and reset().
percentElapsed()
double Timer::percentElapsed ()
Returns the percentage of time that has elapsed since the timer started.
Returns
double The percentage of time elapsed.
Returns
double The percentage of time elapsed.
Definition at line 289 of file Timer.cpp.
{
    int start = 0;
    if (_remainingMilliseconds > _startMilliseconds) {
        start = _remainingMilliseconds;
    } else {
        start = _startMilliseconds;
    }
    if (start == 0) {
        return 100.0;
    }
    int elapsedMilliseconds = start - remainingMilliseconds();
    double percentage = ((double)(elapsedMilliseconds) / start) * 100;
    return percentage;
}
References _remainingMilliseconds, _startMilliseconds, remainingMilliseconds(), and start().
Referenced by Display::tickTimer().
remainingMilliseconds()
int Timer::remainingMilliseconds ()
Returns the remaining time in milliseconds.
If the timer has expired, it returns 0.
Returns
int The remaining time in milliseconds.
If the timer has expired, it returns 0.
Returns
int The remaining time in milliseconds.
Definition at line 251 of file Timer.cpp.
{
    if (_running) {
        auto now = chrono::steady_clock::now();
        auto remaining = chrono::duration_cast<chrono::milliseconds>(_endTime - now).count();
        if (remaining > 0) {
            return remaining;
        } else {
            _running = false;
            _remainingMilliseconds = 0;
            return 0;
        }
    } else {
        return _remainingMilliseconds;
    }
}
References _endTime, _remainingMilliseconds, and _running.
Referenced by Menu::checkTimerInput(), percentElapsed(), Menu::start(), and Display::tickTimer().
reset()
void Timer::reset ()
Resets the timer to its original duration and pauses it.
Definition at line 133 of file Timer.cpp.
                  {
    pause();
    _remainingMilliseconds = _startMilliseconds;
    _countdownMilliseconds = _startMilliseconds;
}
References _countdownMilliseconds, _remainingMilliseconds, _startMilliseconds, and pause().
Referenced by Menu::checkTimerInput().
resume()
void Timer::resume ()
Resumes the timer from where it was paused by recalculating the end time.
Definition at line 120 of file Timer.cpp.
                   {
    if (!_running) {
        _endTime = chrono::steady_clock::now() + chrono::milliseconds(_remainingMilliseconds);
        _running = true;
    }
}
References _endTime, _remainingMilliseconds, and _running.
Referenced by addTime(), and Menu::checkTimerInput().
start()
void Timer::start (int countdownMilliseconds)
Starts the timer by setting the end time based on the current time plus the countdown duration.
Parameters
countdownMilliseconds The duration for the countdown in milliseconds.
Parameters
countdownMilliseconds The duration for the countdown in milliseconds.
Definition at line 93 of file Timer.cpp.
{
    _running = true;
    _endTime = chrono::steady_clock::now() + chrono::milliseconds(_countdownMilliseconds);
}
References _countdownMilliseconds, _endTime, and _running.
Referenced by percentElapsed(), and Timer().
Field Documentation
_countdownMilliseconds
int Timer::_countdownMilliseconds private
The duration of the countdown in milliseconds.
Definition at line 99 of file Timer.hpp.
Referenced by addTime(), reset(), start(), and Timer().
_endTime
chrono::time_point<chrono::steady_clock> Timer::_endTime private
The time point when the timer will end.
Definition at line 105 of file Timer.hpp.
Referenced by pause(), remainingMilliseconds(), resume(), and start().
_incrementMilliseconds
int Timer::_incrementMilliseconds private
The increment time in milliseconds for adding time.
Definition at line 101 of file Timer.hpp.
Referenced by addTime(), changeIncrementTime(), and Timer().
_pauseTime
chrono::time_point<chrono::steady_clock> Timer::_pauseTime private
The time point when the timer was paused.
Definition at line 106 of file Timer.hpp.
Referenced by pause().
_remainingMilliseconds
int Timer::_remainingMilliseconds private
The remaining time in milliseconds.
Definition at line 100 of file Timer.hpp.
Referenced by addTime(), pause(), percentElapsed(), remainingMilliseconds(), reset(), resume(), and Timer().
_running
bool Timer::_running private
Indicates whether the timer is currently running.
Definition at line 103 of file Timer.hpp.
Referenced by addTime(), isRunning(), pause(), remainingMilliseconds(), resume(), and start().
_startMilliseconds
int Timer::_startMilliseconds private
The initial duration of the timer in milliseconds.
Definition at line 98 of file Timer.hpp.
Referenced by percentElapsed(), reset(), and Timer().
The documentation for this class was generated from the following files:
include/Timer.hpp
src/Timer.cpp