Tempo: Display Class Reference
Display Class Reference
The Display class manages the visual representation and interaction logic for timers, stopwatches, and alarms.
#include <Display.hpp>
Public Member Functions
Display ()
Constructs a new Display object.
void tickTimerSetup (string to_print)
Updates the timer setup display, showing the current input with a blinking cursor.
void tickAlarmSetup (string to_print, bool isAM)
Updates the alarm setup display, showing the current input with a blinking cursor.
void tickTimer (Timer &timer)
Updates the display based on the state of the provided Timer object.
void tickStopwatch (Stopwatch &stopwatch)
Updates the display based on the state of the provided Stopwatch object.
void tickAlarm (Alarm &alarm)
Updates the display based on the state of the provided Alarm object.
void stageTimerDisplay (int hours, int minutes, int seconds, int tenths)
Stages the timer display with provided time values.
void stageAlarmDisplay (string time)
Converts the alarm time into an ASCII representation and stages it for display.
void stageArt (vector< string > art)
Stages the controls for the timer.
void stageTimerBar (double percentage)
Stages the progress bar for the timer.
void stageAlarmBar (double percentage)
Creates a visual progress bar for the alarm based on the percentage completed.
void stageStopwatchDisplay (int hours, int minutes, int seconds, int hundredths)
Stages the stopwatch display with provided time values.
void stageStopwatchSplits (vector< int > splits)
Stages the splits block to be displayed.
void stageAlarmDisplay ()
Stages the display for the alarm.
void setSplash (string str)
Sets the splash screen text.
void clearSplash ()
Clears the splash screen.
void printSplash (int splashIndex, string formatting)
Prints the splash screen to the terminal.
void printAscii (int asciiIndex, string formatting)
Prints ASCII art to the terminal.
void printArt (int controlIndex, string formatting)
Prints controls to the terminal.
void printBar (int barIndex, string formatting)
Prints the progress bar to the terminal.
void printSplits (int splitsIndex, string formatting)
Prints the stopwatch splits to the terminal.
void clearScreen ()
Clears the terminal screen.
void setFormat (const string &code)
Sets the terminal text color.
void clearFormat ()
Clears the terminal text color.
void setCursor (int x, int y)
Sets the cursor position in the terminal.
void clearLine (int lineIndex)
Clears a specific line in the terminal.
void setFont (int num)
Sets the font style for the terminal.
Static Public Member Functions
template<typename char_type >
static auto fast_print (const basic_string< char_type > &sss) -> void
Efficiently prints a string to the terminal.
Static Public Attributes
static const string SELECTED = "\033[1;30;46m"
static const string BOLD = "\033[1m"
static const string BLACK = "\033[30m"
static const string RED = "\033[31m"
static const string GREEN = "\033[32m"
static const string YELLOW = "\033[33m"
static const string BLUE = "\033[34m"
static const string MAGENTA = "\033[35m"
static const string CYAN = "\033[36m"
static const string WHITE = "\033[37m"
static const string BOLD_BLACK = "\033[1;30m"
static const string BOLD_RED = "\033[1;31m"
static const string BOLD_GREEN = "\033[1;32m"
static const string BOLD_YELLOW = "\033[1;33m"
static const string BOLD_BLUE = "\033[1;34m"
static const string BOLD_MAGENTA = "\033[1;35m"
static const string BOLD_CYAN = "\033[1;36m"
static const string BOLD_WHITE = "\033[1;37m"
Private Attributes
string _asciiBuffer
Buffer for ASCII art.
string _barBuffer
Buffer for progress bar.
string _controlBuffer
Buffer for controls.
string _splitBuffer
Buffer for the splits block.
string _splash
String for splash screen.
string _oldAscii
Previous ASCII art for comparison.
string _oldControls
Previous controls for comparison.
string _oldBar
Previous progress bar for comparison.
string _oldSplash
Previous splash screen for comparison.
string _oldSplits
Previous splits for comparison.
vector< vector< vector< string > > > _fonts
List of font ascii.
vector< int > _fontHeights
List of font heights.
vector< vector< string > > _currFont
current font ascii
int ASCII_HEIGHT
string PADDING
string _formatting
string _oldFormatting
int _asciiWidth
Width of the ASCII art.
vector< string > _timerSetupControls
vector< string > _alarmSetupControls
vector< string > _alarmSetupAM
vector< string > _alarmSetupPM
vector< string > _alarmControls
vector< string > _timerControls
vector< string > _stopwatchControls
Detailed Description
The Display class manages the visual representation and interaction logic for timers, stopwatches, and alarms.
Handles the terminal display for a timer and stopwatch, including ASCII art and controls.
Definition at line 23 of file Display.hpp.
Constructor & Destructor Documentation
Display()
Display::Display ()
Constructs a new Display object.
Definition at line 39 of file Display.cpp.
{
    _splash = "";
    _asciiBuffer = "";
    _barBuffer = "";
    _controlBuffer = "";
    _splitBuffer = "";
    _oldAscii = "";
    _oldControls = "";
    _oldSplash = "";
    _oldSplits = "";
    _fonts = {f1_ascii, f2_ascii, f3_ascii, f4_ascii};
    _fontHeights = {f1_height, f2_height, f3_height, f4_height};
    setFont(1);
    _asciiWidth = 0;
}
References _asciiBuffer, _asciiWidth, _barBuffer, _controlBuffer, _fontHeights, _fonts, _oldAscii, _oldControls, _oldSplash, _oldSplits, _splash, _splitBuffer, f1_ascii, f1_height, f2_ascii, f2_height, f3_ascii, f3_height, f4_ascii, f4_height, and setFont().
Member Function Documentation
clearFormat()
void Display::clearFormat ()
Clears the terminal text color.
Clears the formatting for the text to be displayed.
Definition at line 147 of file Display.cpp.
{
    _oldFormatting = _formatting;
    _formatting = "\033[0m";
    fast_print(_formatting);
}
References _formatting, _oldFormatting, and fast_print().
Referenced by Menu::credits(), printArt(), Menu::printArt(), printAscii(), printBar(), printSplash(), printSplits(), tickAlarm(), and tickStopwatch().
clearLine()
void Display::clearLine (int row)
Clears a specific line in the terminal.
Parameters
lineIndex The index of the line to clear.
row The row number to clear.
Definition at line 111 of file Display.cpp.
{
    string clearline = "\033[K";
    setCursor(row, 1);
    fast_print(clearline);
}
References fast_print(), and setCursor().
Referenced by printSplash(), and test_nonreturn().
clearScreen()
void Display::clearScreen ()
Clears the terminal screen.
Clears the terminal screen and resets the old buffers.
Definition at line 67 of file Display.cpp.
{
    string clearscreen = "\033[2J\033[H";
    _oldAscii = "";
    _oldControls = "";
    _oldSplash = "";
    _oldBar = "";
    fast_print(clearscreen);
}
References _oldAscii, _oldBar, _oldControls, _oldSplash, and fast_print().
Referenced by Menu::alarmSequence(), Menu::checkAlarmInput(), Menu::checkStopwatchInput(), Menu::checkTimerInput(), Menu::createAlarm(), Menu::createTimer(), Menu::credits(), Menu::mainMenu(), Menu::Menu(), Menu::stopwatchSequence(), test_nonreturn(), and Menu::timerSequence().
clearSplash()
void Display::clearSplash ()
Clears the splash screen.
Clears the splash text from the screen.
Definition at line 170 of file Display.cpp.
{
    _splash = "";
}
References _splash.
Referenced by Menu::checkAlarmInput(), Menu::checkStopwatchInput(), Menu::checkTimerInput(), and test_nonreturn().
fast_print()
template<typename char_type > auto Display::fast_print (const basic_string< char_type > & sss) -> void static
Efficiently prints a string to the terminal.
Prints a string to the console efficiently using the Windows API.
Template Parameters
char_type The character type of the string.
Parameters
sss The string to print.
Template Parameters
char_type The character type (either char or wchar_t).
Parameters
sss The string to print.
Definition at line 124 of file Display.cpp.
{
    HANDLE const output_handle = GetStdHandle(STD_OUTPUT_HANDLE);
    const auto char_count = static_cast<DWORD>(sss.length());
    if constexpr (std::is_same_v<char_type, char>)
        WriteConsoleA(output_handle, sss.c_str(), char_count, nullptr, nullptr);
    else
        WriteConsoleW(output_handle, sss.c_str(), char_count, nullptr, nullptr);
}
Referenced by clearFormat(), clearLine(), clearScreen(), printArt(), printAscii(), printBar(), printSplash(), printSplits(), setCursor(), setFormat(), and test_nonreturn().
printArt()
void Display::printArt (int row, string formatting)
Prints controls to the terminal.
Prints the controls for the timer or stopwatch to the terminal.
Parameters
controlIndex The index used for control display.
row The row position to print.
Definition at line 588 of file Display.cpp.
{
    setFormat(formatting);
    if (_controlBuffer != _oldControls || _formatting != _oldFormatting)
    {
        setCursor(row, 1);
        fast_print(_controlBuffer);
        _oldControls = _controlBuffer;
    }
    _controlBuffer = "";
    clearFormat();
}
References _controlBuffer, _formatting, _oldControls, _oldFormatting, clearFormat(), fast_print(), setCursor(), and setFormat().
Referenced by tickAlarm(), tickAlarmSetup(), tickStopwatch(), tickTimer(), and tickTimerSetup().
printAscii()
void Display::printAscii (int row, string formatting)
Prints ASCII art to the terminal.
Prints the ASCII art representation of the timer or stopwatch to the terminal.
Parameters
asciiIndex The index used for ASCII control.
row The row position to print.
Definition at line 569 of file Display.cpp.
{
    setFormat(formatting);
    if (_asciiBuffer != _oldAscii || _formatting != _oldFormatting)
    {
        setCursor(row, 1);
        fast_print(_asciiBuffer);
        _oldAscii = _asciiBuffer;
    }
    _asciiBuffer = "";
    clearFormat();
}
References _asciiBuffer, _formatting, _oldAscii, _oldFormatting, clearFormat(), fast_print(), setCursor(), and setFormat().
Referenced by tickAlarm(), tickAlarmSetup(), tickStopwatch(), tickTimer(), and tickTimerSetup().
printBar()
void Display::printBar (int row, string formatting)
Prints the progress bar to the terminal.
Prints the progress bar for the timer to the terminal.
Parameters
barIndex The index used for bar control.
row The row position to print.
Definition at line 607 of file Display.cpp.
{
    setFormat(formatting);
    if (_barBuffer != _oldBar || _formatting != _oldFormatting)
    {
        setCursor(row, 1);
        fast_print(_barBuffer);
        _oldBar = _barBuffer;
    }
    _barBuffer = "";
    clearFormat();
}
References _barBuffer, _formatting, _oldBar, _oldFormatting, clearFormat(), fast_print(), setCursor(), and setFormat().
Referenced by tickAlarm(), and tickTimer().
printSplash()
void Display::printSplash (int row, string formatting)
Prints the splash screen to the terminal.
Prints the splash text to the terminal.
Parameters
splashIndex The index used for splash screen control.
row The row position to print.
Definition at line 626 of file Display.cpp.
{
    setFormat(formatting);
    if (_splash != _oldSplash || _formatting != _oldFormatting)
    {
        clearLine(row);
        setCursor(row, 1);
        fast_print(_splash);
        _oldSplash = _splash;
    }
    clearFormat();
}
References _formatting, _oldFormatting, _oldSplash, _splash, clearFormat(), clearLine(), fast_print(), setCursor(), and setFormat().
Referenced by tickAlarm(), tickStopwatch(), and tickTimer().
printSplits()
void Display::printSplits (int row, string formatting)
Prints the stopwatch splits to the terminal.
Parameters
row The row position to print.
Definition at line 645 of file Display.cpp.
{
    setFormat(formatting);
    if (_splitBuffer != _oldSplits || _formatting != _oldFormatting)
    {
        setCursor(row, 1);
        fast_print(_splitBuffer);
        _oldSplits = _splitBuffer;
    }
    _splitBuffer = "";
    clearFormat();
}
References _formatting, _oldFormatting, _oldSplits, _splitBuffer, clearFormat(), fast_print(), setCursor(), and setFormat().
Referenced by tickStopwatch().
setCursor()
void Display::setCursor (int row, int col)
Sets the cursor position in the terminal.
Parameters
x The x-coordinate (column) to move the cursor to.
y The y-coordinate (row) to move the cursor to.
row The row position.
col The column position.
Definition at line 101 of file Display.cpp.
{
    string setcursor = "\033[" + to_string(row) + ";" + to_string(col) + "H";
    fast_print(setcursor);
}
References fast_print().
Referenced by clearLine(), Menu::credits(), Menu::mainMenu(), printArt(), printAscii(), printBar(), printSplash(), printSplits(), Menu::settingsMenu(), test_nonreturn(), tickAlarm(), tickAlarmSetup(), tickStopwatch(), tickTimer(), and tickTimerSetup().
setFont()
void Display::setFont (int num)
Sets the font style for the terminal.
Parameters
num The font style to set.
Definition at line 79 of file Display.cpp.
{
    _currFont = _fonts.at(num-1);
    ASCII_HEIGHT = _fontHeights.at(num-1);
    if(ASCII_HEIGHT >= 8){
        PADDING = "";
        for(int i=0; i< ASCII_HEIGHT/4; i++){
            PADDING += " ";
        }
    }
    else{
        PADDING = "";
    }
}
References _currFont, _fontHeights, _fonts, ASCII_HEIGHT, and PADDING.
Referenced by Display(), Menu::Menu(), and Menu::settingsMenu().
setFormat()
void Display::setFormat (const string & code)
Sets the terminal text color.
Sets the formatting for the text to be displayed.
Parameters
color The color to set the text to.
Template Parameters
code string& The formatting code.
Definition at line 138 of file Display.cpp.
{
    _oldFormatting = _formatting;
    _formatting = code;
    fast_print(_formatting);
}
References _formatting, _oldFormatting, and fast_print().
Referenced by Menu::credits(), printArt(), Menu::printArt(), printAscii(), printBar(), printSplash(), and printSplits().
setSplash()
void Display::setSplash (string str)
Sets the splash screen text.
Sets the splash text to be displayed at the top or bottom of the screen.
Parameters
str The string to display as the splash screen.
str The splash text to display.
Definition at line 162 of file Display.cpp.
{
    _splash = "<< " + str + " >>";
}
References _splash.
Referenced by Menu::alarmSequence(), Menu::checkStopwatchInput(), Menu::checkTimerInput(), Menu::stopwatchSequence(), test_nonreturn(), and Menu::timerSequence().
stageAlarmBar()
void Display::stageAlarmBar (double percentage)
Creates a visual progress bar for the alarm based on the percentage completed.
Parameters
percentage The percentage of completion.
Definition at line 356 of file Display.cpp.
{
    int width = _asciiWidth - 2;
    int filled = (int)((percentage / 100) * width);
    string border = "";
    // Build the top and bottom borders of the bar
    border += "+";
    for (int i = 0; i < width; ++i)
    {
        border += "-";
    }
    border += "+\n";
    _barBuffer += border;
    _barBuffer += "|";
    // Fill the bar with '#' characters based on the percentage completed
    for (int i = 0; i < width; ++i)
    {
        if (i < filled)
        {
            _barBuffer += "#";
        }
        else
        {
            _barBuffer += " ";
        }
    }
    _barBuffer += "|\n";
    _barBuffer += border;
}
References _asciiWidth, and _barBuffer.
Referenced by tickAlarm().
stageAlarmDisplay() [1/2]
void Display::stageAlarmDisplay ()
Stages the display for the alarm.
Referenced by tickAlarm().
stageAlarmDisplay() [2/2]
void Display::stageAlarmDisplay (string time)
Converts the alarm time into an ASCII representation and stages it for display.
Parameters
time The alarm time string in "HH:MM" format.
Definition at line 247 of file Display.cpp.
{
    string to_print = "";
    int hours = stoi(time.substr(0,2));
    int minutes = stoi(time.substr(3,2));
    // Determine AM/PM and convert 24-hour format to 12-hour format
    string period = (hours >= 12) ? "pm" : "am";
    hours = hours % 12; // Convert 24-hour to 12-hour format
    if (hours == 0) { hours = 12; } // Handle the case where hour is 0 (midnight or noon)
    to_print += to_string(hours) + ":";
    // Add leading zero to minutes if needed
    if (int(minutes / 10) != 0)
    {
        to_print += to_string(minutes);
    }
    else
    {
        to_print += "0" + to_string(minutes);
    }
    // Add " am" or " pm"
    to_print += period;
    // Build the ASCII art for the alarm display
    for (int i = 0; i < ASCII_HEIGHT; i++)
    {
        string line;
        for (char ch : to_print)
        {
            if (ch == ':')
            {
                line += _currFont.at(10)[i];
                line += PADDING;
            }
            else if (ch == 'a')
            {
                line += _currFont.at(12)[i];
                line += PADDING;
            }
            else if (ch == 'p')
            {
                line += _currFont.at(13)[i];
                line += PADDING;
            }
            else if (ch == 'm')
            {
                line += _currFont.at(14)[i];
                line += PADDING;
            }
            else
            {
                line += _currFont.at(ch - '0')[i];
                line += PADDING;
            }
        }
        _asciiWidth = line.length();
        _asciiBuffer += (line + "\n");
    }
}
References _asciiBuffer, _asciiWidth, _currFont, ASCII_HEIGHT, and PADDING.
stageArt()
void Display::stageArt (vector< string > art)
Stages the controls for the timer.
Stages vector<string> ascii art to be displayed in the terminal.
Definition at line 396 of file Display.cpp.
{
    for(int i=0; i<art.size(); ++i){
        _controlBuffer += (art.at(i) + "\n");
    }
}
References _controlBuffer.
Referenced by tickAlarm(), tickAlarmSetup(), tickStopwatch(), tickTimer(), and tickTimerSetup().
stageStopwatchDisplay()
void Display::stageStopwatchDisplay (int hours, int minutes, int seconds, int hundredths)
Stages the stopwatch display with provided time values.
Converts the stopwatch values into an ASCII representation and stages it for display.
Parameters
hours Hours to display.
minutes Minutes to display.
seconds Seconds to display.
hundredths Hundredths of a second to display.
hours The number of hours.
minutes The number of minutes.
seconds The number of seconds.
hundredths The number of hundredths of a second.
Definition at line 414 of file Display.cpp.
{
    string to_print = "";
    // Only show hours if there are more than 0
    if (hours != 0)
    {
        to_print += to_string(hours) + ":";
    }
    // Show minutes with a leading zero if needed
    if (hours)
    {
        if (int(minutes / 10) != 0)
        {
            to_print += to_string(minutes) + ":";
        }
        else
        {
            to_print += "0" + to_string(minutes) + ":";
        }
    }
    else if (minutes)
    {
        to_print += to_string(minutes) + ":";
    }
    // Show seconds with a leading zero if needed
    if (hours || minutes)
    {
        if (int(seconds / 10) != 0)
        {
            to_print += to_string(seconds);
        }
        else
        {
            to_print += "0" + to_string(seconds);
        }
    }
    else
    {
        to_print += to_string(seconds);
    }
    // Show hundredths of a second if there are no hours
    if (hours == 0)
    {
        to_print += ".";
        if (int(hundredths / 10) != 0)
        {
            to_print += to_string(hundredths);
        }
        else
        {
            to_print += "0" + to_string(hundredths);
        }
    }
    // Build the ASCII art for the stopwatch display
    for (int i = 0; i < ASCII_HEIGHT; i++)
    {
        string line;
        for (char ch : to_print)
        {
            if (ch == ':')
            {
                line += _currFont.at(10)[i]; // Colon character
                line += PADDING;
            }
            else if (ch == '.')
            {
                line += _currFont.at(11)[i]; // Period character
                line += PADDING;
            }
            else
            {
                line += _currFont.at(ch - '0')[i]; // Numeric character
                line += PADDING;
            }
        }
        _asciiBuffer += (line + "\n");
    }
}
References _asciiBuffer, _currFont, ASCII_HEIGHT, and PADDING.
Referenced by tickStopwatch().
stageStopwatchSplits()
void Display::stageStopwatchSplits (vector< int > splits)
Stages the splits block to be displayed.
Definition at line 501 of file Display.cpp.
{
    if (!splits.empty()) {
        _splitBuffer += "  SPLITS:\n\n";
        int startIdx = (splits.size() > 10) ? splits.size() - 10 : 0;
        for (int i = startIdx; i < splits.size(); ++i) {
            int milliseconds = splits.at(i);
            int hours = milliseconds / 3600000;
            milliseconds %= 3600000;
            int minutes = milliseconds / 60000;
            milliseconds %= 60000;
            int seconds = milliseconds / 1000;
            milliseconds %= 1000;
            int hundredths = milliseconds / 10;
            string to_print = "";
            // Only show hours if there are more than 0
            if (hours != 0) {
                to_print += to_string(hours) + ":";
            }
            // Show minutes with a leading zero if needed
            if (hours) {
                if (int(minutes / 10) != 0) {
                    to_print += to_string(minutes) + ":";
                } else {
                    to_print += "0" + to_string(minutes) + ":";
                }
            } else if (minutes) {
                to_print += to_string(minutes) + ":";
            }
            // Show seconds with a leading zero if needed
            if (hours || minutes) {
                if (int(seconds / 10) != 0) {
                    to_print += to_string(seconds);
                } else {
                    to_print += "0" + to_string(seconds);
                }
            } else {
                to_print += to_string(seconds);
            }
            // Show hundredths of a second if there are no hours
            if (hours == 0) {
                to_print += ".";
                if (int(hundredths / 10) != 0) {
                    to_print += to_string(hundredths);
                } else {
                    to_print += "0" + to_string(hundredths);
                }
            }
            string fullprint = "Split " + to_string(i + 1) + ": " + to_print + "\n";
            _splitBuffer += fullprint;
        }
    } else {
        _splitBuffer = "";
    }
}
References _splitBuffer.
Referenced by tickStopwatch().
stageTimerBar()
void Display::stageTimerBar (double percentage)
Stages the progress bar for the timer.
Creates a visual progress bar for the timer based on the percentage completed.
Parameters
percentage The percentage of the timer's progress to display.
percentage The percentage of completion.
Definition at line 316 of file Display.cpp.
{
    int width = _asciiWidth - 2;
    int filled = (int)((percentage / 100) * width);
    string border = "";
    // Build the top and bottom borders of the bar
    border += "+";
    for (int i = 0; i < width; ++i)
    {
        border += "-";
    }
    border += "+\n";
    _barBuffer += border;
    _barBuffer += "|";
    // Fill the bar with '#' characters based on the percentage completed
    for (int i = 0; i < width; ++i)
    {
        if (i < filled)
        {
            _barBuffer += "#";
        }
        else
        {
            _barBuffer += " ";
        }
    }
    _barBuffer += "|\n";
    _barBuffer += border;
}
References _asciiWidth, and _barBuffer.
Referenced by tickTimer().
stageTimerDisplay()
void Display::stageTimerDisplay (int hours, int minutes, int seconds, int tenths)
Stages the timer display with provided time values.
Converts the timer values into an ASCII representation and stages it for display.
Parameters
hours Hours to display.
minutes Minutes to display.
seconds Seconds to display.
tenths Tenths of a second to display.
hours The number of hours.
minutes The number of minutes.
seconds The number of seconds.
tenths The number of tenths of a second.
Definition at line 186 of file Display.cpp.
{
    string to_print = "";
    // Only display hours if there is at least 1 hour left
    if (hours != 0)
    {
        to_print += to_string(hours) + ":";
    }
    // Add leading zero to minutes if needed
    if (int(minutes / 10) != 0)
    {
        to_print += to_string(minutes) + ":";
    }
    else
    {
        to_print += "0" + to_string(minutes) + ":";
    }
    // Add leading zero to seconds if needed
    if (int(seconds / 10) != 0)
    {
        to_print += to_string(seconds);
    }
    else
    {
        to_print += "0" + to_string(seconds);
    }
    // Build the ASCII art for the timer display
    for (int i = 0; i < ASCII_HEIGHT; i++)
    {
        string line;
        for (char ch : to_print)
        {
            if (ch == ':')
            {
                line += _currFont.at(10)[i]; // Colon character
                line += PADDING;
            }
            else if (ch == '.')
            {
                line += _currFont.at(11)[i]; // Period character
                line += PADDING;
            }
            else
            {
                line += _currFont.at(ch - '0')[i]; // Numeric character
                line += PADDING;
            }
        }
        _asciiWidth = line.length(); // Update ASCII width
        _asciiBuffer += (line + "\n");
    }
}
References _asciiBuffer, _asciiWidth, _currFont, ASCII_HEIGHT, and PADDING.
Referenced by tickTimer().
tickAlarm()
void Display::tickAlarm (Alarm & alarm)
Updates the display based on the state of the provided Alarm object.
Updates the alarm display on each tick, showing the alarm time and progress bar.
Parameters
alarm Reference to the Alarm object.
alarm The Alarm object to get the alarm time and progress from.
Definition at line 899 of file Display.cpp.
{
    auto now = std::chrono::steady_clock::now();
    auto millis = std::chrono::duration_cast<std::chrono::milliseconds>(now.time_since_epoch()).count();
    bool flash = ((millis / 500) % 2 == 0);
    string time = alarm.timeToString(alarm.getEndTime()).substr(0,5);
    stageAlarmDisplay(time);
    stageAlarmBar(alarm.percentElapsed());
    stageArt(_alarmControls);
    string temp;
    if(alarm.isDone() && flash){
        temp = BOLD_RED;
    }
    else{
        temp = BOLD_WHITE;
    }
    printAscii(1, temp);
    printBar(ASCII_HEIGHT+2, temp);
    printArt(ASCII_HEIGHT+5, BOLD_CYAN);
    printSplash(ASCII_HEIGHT+8, WHITE);
    clearFormat();
    setCursor(1,1);
    return;
}
References _alarmControls, ASCII_HEIGHT, BOLD_CYAN, BOLD_RED, BOLD_WHITE, clearFormat(), Alarm::getEndTime(), Alarm::isDone(), Alarm::percentElapsed(), printArt(), printAscii(), printBar(), printSplash(), setCursor(), stageAlarmBar(), stageAlarmDisplay(), stageArt(), Alarm::timeToString(), and WHITE.
Referenced by Menu::alarmSequence(), and test_alarm().
tickAlarmSetup()
void Display::tickAlarmSetup (string to_print, bool isAM)
Updates the alarm setup display, showing the current input with a blinking cursor.
Parameters
to_print The current alarm setup input string.
Definition at line 705 of file Display.cpp.
{
    auto now = std::chrono::steady_clock::now();
    auto millis = std::chrono::duration_cast<std::chrono::milliseconds>(now.time_since_epoch()).count();
    int tempHeight;
    bool showBar = ((millis / 500) % 2 == 0);
    if(ASCII_HEIGHT < 4){
        tempHeight = 4;
    }
    else{
        tempHeight = ASCII_HEIGHT;
    }
    for (int i = 0; i < tempHeight; i++)
    {
        string line;
        line += BOLD_WHITE;
        for (char ch : to_print)
        {
            if (ch == ':')
            {
                line += _currFont.at(10)[i]; // Colon character
                line += PADDING;
            }
            else
            {
                line += _currFont.at(ch - '0')[i]; // Numeric character
                line += PADDING;
            }
        }
        if(showBar){
            line += " | ";
        }
        else{
            line += "   ";
        }
        int linesLeft = tempHeight - i;
        if(linesLeft <= 4){
            line += "  ";
            if(isAM){
                line += SELECTED;
            }
            else{
                line += BOLD_WHITE;
            }
            line += _alarmSetupAM[4-linesLeft];
            line += "\033[0m";
            line += "  ";
            if(!isAM){
                line += SELECTED;
            }
            else{
                line += BOLD_WHITE;
            }
            line += _alarmSetupPM[4-linesLeft];
            line += "\033[0m";
        }
        _asciiWidth = line.length(); // Update ASCII width
        _asciiBuffer += (line + "\n");
    }
    stageArt(_alarmSetupControls);
    printArt(1, BOLD_CYAN);
    printAscii(5,BOLD_WHITE);
    /*
    stageArt(_alarmSetupAM);
    if(isAM){
        printArt(ASCII_HEIGHT + 6, SELECTED);
        stageArt(_alarmSetupPM);
        printArt(ASCII_HEIGHT + 10, BOLD_WHITE);
    }
    else{
        printArt(ASCII_HEIGHT + 6, BOLD_WHITE);
        stageArt(_alarmSetupPM);
        printArt(ASCII_HEIGHT + 10, SELECTED);
    }
    */
    setCursor(1,1);
}
References _alarmSetupAM, _alarmSetupControls, _alarmSetupPM, _asciiBuffer, _asciiWidth, _currFont, ASCII_HEIGHT, BOLD_CYAN, BOLD_WHITE, PADDING, printArt(), printAscii(), SELECTED, setCursor(), and stageArt().
Referenced by Menu::createAlarm(), and test_alarm_setup().
tickStopwatch()
void Display::tickStopwatch (Stopwatch & stopwatch)
Updates the display based on the state of the provided Stopwatch object.
Updates the stopwatch display on each tick, converting time into ASCII and updating the terminal.
Parameters
stopwatch Reference to the Stopwatch object.
stopwatch The Stopwatch object to get the current time from.
Definition at line 856 of file Display.cpp.
{
    int milliseconds = stopwatch.currentMilliseconds();
    int hours = milliseconds / 3600000;
    milliseconds %= 3600000;
    int minutes = milliseconds / 60000;
    milliseconds %= 60000;
    int seconds = milliseconds / 1000;
    milliseconds %= 1000;
    int hundredths = milliseconds / 10;
    stageStopwatchDisplay(hours, minutes, seconds, hundredths);
    stageArt(_stopwatchControls);
    stageStopwatchSplits(stopwatch.getSplits());
    string temp;
    if(!stopwatch.isRunning()){
        if ((stopwatch.currentMilliseconds() / 10) % 100 == 0 && stopwatch.currentMilliseconds() != 0){
            temp = BOLD_GREEN;
        }
        else{
            temp = BOLD_RED;
        }
    }
    else{
        temp = BOLD_WHITE;
    }
    printAscii(1, temp);
    printArt(ASCII_HEIGHT+1, BOLD_CYAN);
    printSplash(ASCII_HEIGHT+4, WHITE);
    printSplits(ASCII_HEIGHT+6, WHITE);
    clearFormat();
    setCursor(1,1);
}
References _stopwatchControls, ASCII_HEIGHT, BOLD_CYAN, BOLD_GREEN, BOLD_RED, BOLD_WHITE, clearFormat(), Stopwatch::currentMilliseconds(), Stopwatch::getSplits(), Stopwatch::isRunning(), printArt(), printAscii(), printSplash(), printSplits(), setCursor(), stageArt(), stageStopwatchDisplay(), stageStopwatchSplits(), and WHITE.
Referenced by Menu::stopwatchSequence(), and test_stopwatch().
tickTimer()
void Display::tickTimer (Timer & timer)
Updates the display based on the state of the provided Timer object.
Updates the timer display on each tick, converting time into ASCII and updating the terminal.
Parameters
timer Reference to the Timer object.
timer The Timer object to get the remaining time from.
Definition at line 812 of file Display.cpp.
{
    auto now = std::chrono::steady_clock::now();
    auto millis = std::chrono::duration_cast<std::chrono::milliseconds>(now.time_since_epoch()).count();
    bool flash = ((millis / 500) % 2 == 0);
    int remaining = timer.remainingMilliseconds();
    int hours = remaining / 3600000;
    remaining %= 3600000;
    int minutes = remaining / 60000;
    remaining %= 60000;
    int seconds = remaining / 1000;
    remaining %= 1000;
    int tenths = remaining / 100;
    stageTimerDisplay(hours, minutes, seconds, tenths);
    stageTimerBar(timer.percentElapsed());
    stageArt(_timerControls);
    string temp;
    if(!timer.isRunning()){
        if(timer.isDone() && flash){
            temp = BOLD_WHITE;
        }
        else{
            temp = BOLD_RED;
        }
    }
    else{
        temp = BOLD_WHITE;
    }
    printAscii(1, temp);
    printBar(ASCII_HEIGHT+2, temp);
    printArt(ASCII_HEIGHT+5, BOLD_CYAN);
    printSplash(ASCII_HEIGHT+8, WHITE);
    setCursor(1,1);
}
References _timerControls, ASCII_HEIGHT, BOLD_CYAN, BOLD_RED, BOLD_WHITE, Timer::isDone(), Timer::isRunning(), Timer::percentElapsed(), printArt(), printAscii(), printBar(), printSplash(), Timer::remainingMilliseconds(), setCursor(), stageArt(), stageTimerBar(), stageTimerDisplay(), and WHITE.
Referenced by test_timer(), and Menu::timerSequence().
tickTimerSetup()
void Display::tickTimerSetup (string to_print)
Updates the timer setup display, showing the current input with a blinking cursor.
Parameters
to_print The current timer setup input string.
Definition at line 663 of file Display.cpp.
{
    auto now = std::chrono::steady_clock::now();
    auto millis = std::chrono::duration_cast<std::chrono::milliseconds>(now.time_since_epoch()).count();
    bool showBar = ((millis / 500) % 2 == 0);
    _asciiBuffer.clear(); // Clear buffer before filling it with new content
    for (int i = 0; i < ASCII_HEIGHT; ++i)
    {
        string line;
        for (char ch : to_print)
        {
            if (ch == ':')
            {
                line += _currFont.at(10)[i]; // Colon character
            }
            else
            {
                line += _currFont.at(ch - '0')[i]; // Numeric character
            }
            line += PADDING;
        }
        line += showBar ? " |" : "   "; // Append progress bar indicator
        _asciiWidth = line.length();
        _asciiBuffer += (line + "\n");
    }
    stageArt(_timerSetupControls);
    printArt(1, BOLD_CYAN);
    printAscii(5, BOLD_WHITE);
    setCursor(1,1);
}
References _asciiBuffer, _asciiWidth, _currFont, _timerSetupControls, ASCII_HEIGHT, BOLD_CYAN, BOLD_WHITE, PADDING, printArt(), printAscii(), setCursor(), and stageArt().
Referenced by Menu::createTimer(), and test_timer_setup().
Field Documentation
_alarmControls
vector<string> Display::_alarmControls private
Initial value:
= {
        "",
        "A: New Alarm | Q: Main Menu",
        "",
    }
Definition at line 256 of file Display.hpp.
Referenced by tickAlarm().
_alarmSetupAM
vector<string> Display::_alarmSetupAM private
Initial value:
= {
        "           ",
        "  /\\  |\\/| ",
        " /--\\ |  | ",
        "           ",
    }
Definition at line 241 of file Display.hpp.
Referenced by tickAlarmSetup().
_alarmSetupControls
vector<string> Display::_alarmSetupControls private
Initial value:
= {
        " _     ___ _  _                  _         ___ ___       _   ",
        "|_ |\\ | | |_ |_)    /\\  |   /\\  |_) |\\/|    |   |  |\\/| |_ o ",
        "|_ | \\| | |_ | \\   /--\\ |_ /--\\ | \\ |  |    |  _|_ |  | |_ o ",
    }
Definition at line 235 of file Display.hpp.
Referenced by tickAlarmSetup().
_alarmSetupPM
vector<string> Display::_alarmSetupPM private
Initial value:
= {
        "  _       ",
        " |_) |\\/| ",
        " |   |  | ",
        "          ",
    }
Definition at line 249 of file Display.hpp.
Referenced by tickAlarmSetup().
_asciiBuffer
string Display::_asciiBuffer private
Buffer for ASCII art.
Definition at line 205 of file Display.hpp.
Referenced by Display(), printAscii(), stageAlarmDisplay(), stageStopwatchDisplay(), stageTimerDisplay(), tickAlarmSetup(), and tickTimerSetup().
_asciiWidth
int Display::_asciiWidth private
Width of the ASCII art.
Definition at line 227 of file Display.hpp.
Referenced by Display(), stageAlarmBar(), stageAlarmDisplay(), stageTimerBar(), stageTimerDisplay(), tickAlarmSetup(), and tickTimerSetup().
_barBuffer
string Display::_barBuffer private
Buffer for progress bar.
Definition at line 206 of file Display.hpp.
Referenced by Display(), printBar(), stageAlarmBar(), and stageTimerBar().
_controlBuffer
string Display::_controlBuffer private
Buffer for controls.
Definition at line 207 of file Display.hpp.
Referenced by Display(), printArt(), and stageArt().
_currFont
vector<vector<string> > Display::_currFont private
current font ascii
Definition at line 219 of file Display.hpp.
Referenced by setFont(), stageAlarmDisplay(), stageStopwatchDisplay(), stageTimerDisplay(), tickAlarmSetup(), and tickTimerSetup().
_fontHeights
vector<int> Display::_fontHeights private
List of font heights.
Definition at line 218 of file Display.hpp.
Referenced by Display(), and setFont().
_fonts
vector<vector<vector<string> > > Display::_fonts private
List of font ascii.
Definition at line 217 of file Display.hpp.
Referenced by Display(), and setFont().
_formatting
string Display::_formatting private
Definition at line 224 of file Display.hpp.
Referenced by clearFormat(), printArt(), printAscii(), printBar(), printSplash(), printSplits(), and setFormat().
_oldAscii
string Display::_oldAscii private
Previous ASCII art for comparison.
Definition at line 211 of file Display.hpp.
Referenced by clearScreen(), Display(), and printAscii().
_oldBar
string Display::_oldBar private
Previous progress bar for comparison.
Definition at line 213 of file Display.hpp.
Referenced by clearScreen(), and printBar().
_oldControls
string Display::_oldControls private
Previous controls for comparison.
Definition at line 212 of file Display.hpp.
Referenced by clearScreen(), Display(), and printArt().
_oldFormatting
string Display::_oldFormatting private
Definition at line 225 of file Display.hpp.
Referenced by clearFormat(), printArt(), printAscii(), printBar(), printSplash(), printSplits(), and setFormat().
_oldSplash
string Display::_oldSplash private
Previous splash screen for comparison.
Definition at line 214 of file Display.hpp.
Referenced by clearScreen(), Display(), and printSplash().
_oldSplits
string Display::_oldSplits private
Previous splits for comparison.
Definition at line 215 of file Display.hpp.
Referenced by Display(), and printSplits().
_splash
string Display::_splash private
String for splash screen.
Definition at line 209 of file Display.hpp.
Referenced by clearSplash(), Display(), printSplash(), and setSplash().
_splitBuffer
string Display::_splitBuffer private
Buffer for the splits block.
Definition at line 208 of file Display.hpp.
Referenced by Display(), printSplits(), and stageStopwatchSplits().
_stopwatchControls
vector<string> Display::_stopwatchControls private
Initial value:
= {
        "",
        "S: Start/Stop | R: Reset | A: Add Split | Q: Main Menu",
        "",
    }
Definition at line 268 of file Display.hpp.
Referenced by tickStopwatch().
_timerControls
vector<string> Display::_timerControls private
Initial value:
= {
        "",
        "S: Start/Stop | R: Reset | A: New Timer | Q: Main Menu",
        "",
    }
Definition at line 262 of file Display.hpp.
Referenced by tickTimer().
_timerSetupControls
vector<string> Display::_timerSetupControls private
Initial value:
= {
        "  _     ___ _  _    ___ ___       _  _        _       __ ___      ",
        " |_ |\\ | | |_ |_)    |   |  |\\/| |_ |_)   |  |_ |\\ | /__  | |_| o ",
        " |_ | \\| | |_ | \\    |  _|_ |  | |_ | \\   |_ |_ | \\| \\_|  | | | o ",
    }
Definition at line 229 of file Display.hpp.
Referenced by tickTimerSetup().
ASCII_HEIGHT
int Display::ASCII_HEIGHT private
Definition at line 221 of file Display.hpp.
Referenced by setFont(), stageAlarmDisplay(), stageStopwatchDisplay(), stageTimerDisplay(), tickAlarm(), tickAlarmSetup(), tickStopwatch(), tickTimer(), and tickTimerSetup().
BLACK
const string Display::BLACK = "\033[30m" static
Definition at line 31 of file Display.hpp.
BLUE
const string Display::BLUE = "\033[34m" static
Definition at line 35 of file Display.hpp.
BOLD
const string Display::BOLD = "\033[1m" static
Definition at line 29 of file Display.hpp.
BOLD_BLACK
const string Display::BOLD_BLACK = "\033[1;30m" static
Definition at line 40 of file Display.hpp.
BOLD_BLUE
const string Display::BOLD_BLUE = "\033[1;34m" static
Definition at line 44 of file Display.hpp.
BOLD_CYAN
const string Display::BOLD_CYAN = "\033[1;36m" static
Definition at line 46 of file Display.hpp.
Referenced by Menu::credits(), Menu::mainMenu(), Menu::settingsMenu(), tickAlarm(), tickAlarmSetup(), tickStopwatch(), tickTimer(), and tickTimerSetup().
BOLD_GREEN
const string Display::BOLD_GREEN = "\033[1;32m" static
Definition at line 42 of file Display.hpp.
Referenced by tickStopwatch().
BOLD_MAGENTA
const string Display::BOLD_MAGENTA = "\033[1;35m" static
Definition at line 45 of file Display.hpp.
BOLD_RED
const string Display::BOLD_RED = "\033[1;31m" static
Definition at line 41 of file Display.hpp.
Referenced by tickAlarm(), tickStopwatch(), and tickTimer().
BOLD_WHITE
const string Display::BOLD_WHITE = "\033[1;37m" static
Definition at line 47 of file Display.hpp.
Referenced by Menu::mainMenu(), Menu::Menu(), Menu::settingsMenu(), tickAlarm(), tickAlarmSetup(), tickStopwatch(), tickTimer(), and tickTimerSetup().
BOLD_YELLOW
const string Display::BOLD_YELLOW = "\033[1;33m" static
Definition at line 43 of file Display.hpp.
CYAN
const string Display::CYAN = "\033[36m" static
Definition at line 37 of file Display.hpp.
GREEN
const string Display::GREEN = "\033[32m" static
Definition at line 33 of file Display.hpp.
MAGENTA
const string Display::MAGENTA = "\033[35m" static
Definition at line 36 of file Display.hpp.
PADDING
string Display::PADDING private
Definition at line 222 of file Display.hpp.
Referenced by setFont(), stageAlarmDisplay(), stageStopwatchDisplay(), stageTimerDisplay(), tickAlarmSetup(), and tickTimerSetup().
RED
const string Display::RED = "\033[31m" static
Definition at line 32 of file Display.hpp.
SELECTED
const string Display::SELECTED = "\033[1;30;46m" static
Definition at line 27 of file Display.hpp.
Referenced by Menu::mainMenu(), Menu::settingsMenu(), and tickAlarmSetup().
WHITE
const string Display::WHITE = "\033[37m" static
Definition at line 38 of file Display.hpp.
Referenced by Menu::credits(), tickAlarm(), tickStopwatch(), and tickTimer().
YELLOW
const string Display::YELLOW = "\033[33m" static
Definition at line 34 of file Display.hpp.
The documentation for this class was generated from the following files:
include/Display.hpp
src/Display.cpp