Tempo: Alarm Class Reference
Alarm Class Reference
A class to manage alarms with time-based triggers.
#include <Alarm.hpp>
Public Member Functions
Alarm (int h, int m)
Constructor for the Alarm object.
chrono::time_point< chrono::system_clock > getTime (int h, int m)
Creates the nearest future time point with hours h and minutes m.
string timeToString (chrono::time_point< chrono::system_clock > t)
Converts a given time point to a string format (HH:MM).
chrono::time_point< chrono::system_clock > getStartTime ()
Returns the alarm's start time.
chrono::time_point< chrono::system_clock > getEndTime ()
Returns the alarm's end time.
void start ()
bool isRunning ()
Checks if the alarm is currently running.
bool isDone ()
Checks if the alarm has finished.
int remainingMilliseconds ()
Calculates the remaining time in milliseconds until the alarm ends.
double percentElapsed ()
Calculates the percentage of time that has elapsed from start to end.
Static Public Member Functions
static chrono::time_point< chrono::system_clock > currentTime ()
Returns the current system time.
Private Attributes
int _remainingMilliseconds
bool _running
chrono::time_point< chrono::system_clock > _startTime
chrono::time_point< chrono::system_clock > _endTime
Detailed Description
A class to manage alarms with time-based triggers.
The Alarm class allows setting up an alarm for a future time, checking the progress of time, and determining when the alarm has finished.
Definition at line 13 of file Alarm.hpp.
Constructor & Destructor Documentation
Alarm()
Alarm::Alarm (int h, int m)
Constructor for the Alarm object.
Initializes the alarm with the specified hours and minutes. If the current time is past the set time, it schedules the alarm for the next day.
Parameters
h Hour value for the new alarm (0-23).
m Minute value for the new alarm (0-59).
Definition at line 18 of file Alarm.cpp.
{
    _startTime = currentTime();
    _endTime = getTime(h, m);
    _remainingMilliseconds = 0;
    if(_startTime >= _endTime){
        _endTime = getTime(h+24, m);
    }
    _running = true;
}
References _endTime, _remainingMilliseconds, _running, _startTime, currentTime(), and getTime().
Member Function Documentation
currentTime()
chrono::time_point< chrono::system_clock > Alarm::currentTime () static
Returns the current system time.
Returns
A time point representing the current time.
Definition at line 159 of file Alarm.cpp.
{
    return chrono::system_clock::now();
}
Referenced by Alarm(), getTime(), percentElapsed(), remainingMilliseconds(), and timeToString().
getEndTime()
chrono::time_point< chrono::system_clock > Alarm::getEndTime ()
Returns the alarm's end time.
Returns
Time point representing the end time of the alarm.
Definition at line 123 of file Alarm.cpp.
{
    return _endTime;
}
References _endTime.
Referenced by test_alarm(), and Display::tickAlarm().
getStartTime()
chrono::time_point< chrono::system_clock > Alarm::getStartTime ()
Returns the alarm's start time.
Returns
Time point representing the start time of the alarm.
Definition at line 114 of file Alarm.cpp.
{
    return _startTime;
}
References _startTime.
Referenced by test_alarm().
getTime()
chrono::time_point< chrono::system_clock > Alarm::getTime (int h, int m)
Creates the nearest future time point with hours h and minutes m.
If the specified time has already passed today, this method sets the alarm for the same time on the next day.
Parameters
h Hour value for the new alarm (0-23).
m Minute value for the new alarm (0-59).
Returns
Time point representing the future alarm time.
Definition at line 38 of file Alarm.cpp.
{
    auto now = currentTime();
    time_t currentTime = chrono::system_clock::to_time_t(now);
    tm* localTime = localtime(&currentTime);
    localTime->tm_hour = h;
    localTime->tm_min = m;
    localTime->tm_sec = 0;
    auto futureTime = chrono::system_clock::from_time_t(mktime(localTime));
    return futureTime;
}
References currentTime().
Referenced by Alarm().
isDone()
bool Alarm::isDone ()
Checks if the alarm has finished.
If the remaining milliseconds are less than or equal to 0, the alarm is considered done.
Returns
True if the alarm has completed, false otherwise.
Definition at line 134 of file Alarm.cpp.
                  {
    int remaining = remainingMilliseconds();
    if (remaining > 0) {
        return false;
    } else {
        _running = false;
        _remainingMilliseconds = 0;
        return true;
    }
}
References _remainingMilliseconds, _running, and remainingMilliseconds().
Referenced by Menu::alarmSequence(), test_alarm(), and Display::tickAlarm().
isRunning()
bool Alarm::isRunning ()
Checks if the alarm is currently running.
Returns
True if the alarm is running, false otherwise.
Definition at line 150 of file Alarm.cpp.
                      {
    return _running;
}
References _running.
Referenced by test_alarm().
percentElapsed()
double Alarm::percentElapsed ()
Calculates the percentage of time that has elapsed from start to end.
This method calculates the percentage of time passed relative to the alarm's start and end times.
Returns
The percentage of time elapsed as a double.
Definition at line 78 of file Alarm.cpp.
{
    auto totalMilliseconds = chrono::duration_cast<chrono::milliseconds>(_endTime - _startTime).count();
    if (totalMilliseconds == 0) {
        return 100.0;
    }
    auto now = currentTime();
    auto elapsedMilliseconds = chrono::duration_cast<chrono::milliseconds>(now - _startTime).count();
    if (elapsedMilliseconds >= totalMilliseconds) {
        return 100.0;
    }
    double percentage = (static_cast<double>(elapsedMilliseconds) / totalMilliseconds) * 100.0;
    return percentage;
}
References _endTime, _startTime, and currentTime().
Referenced by test_alarm(), and Display::tickAlarm().
remainingMilliseconds()
int Alarm::remainingMilliseconds ()
Calculates the remaining time in milliseconds until the alarm ends.
Returns
Remaining milliseconds until the alarm ends.
Definition at line 102 of file Alarm.cpp.
{
    auto now = currentTime();
    auto ms = chrono::duration_cast<chrono::milliseconds>(_endTime - now).count();
    return ms;
}
References _endTime, and currentTime().
Referenced by isDone(), and test_alarm().
start()
void Alarm::start ()
timeToString()
string Alarm::timeToString (chrono::time_point< chrono::system_clock > t)
Converts a given time point to a string format (HH:MM).
Parameters
t Time point to convert to string.
Returns
A string representing the time in HH:MM format.
Definition at line 59 of file Alarm.cpp.
{
    time_t currentTime = chrono::system_clock::to_time_t(t);
    tm* localTime = localtime(&currentTime);
    stringstream ss;
    ss << setw(2) << setfill('0') << localTime->tm_hour << ":"
       << setw(2) << setfill('0') << localTime->tm_min;
    return ss.str();
}
References currentTime().
Referenced by test_alarm(), and Display::tickAlarm().
Field Documentation
_endTime
chrono::time_point<chrono::system_clock> Alarm::_endTime private
Definition at line 42 of file Alarm.hpp.
Referenced by Alarm(), getEndTime(), percentElapsed(), and remainingMilliseconds().
_remainingMilliseconds
int Alarm::_remainingMilliseconds private
Definition at line 37 of file Alarm.hpp.
Referenced by Alarm(), and isDone().
_running
bool Alarm::_running private
Definition at line 39 of file Alarm.hpp.
Referenced by Alarm(), isDone(), and isRunning().
_startTime
chrono::time_point<chrono::system_clock> Alarm::_startTime private
Definition at line 41 of file Alarm.hpp.
Referenced by Alarm(), getStartTime(), and percentElapsed().
The documentation for this class was generated from the following files:
include/Alarm.hpp
src/Alarm.cpp